{{- if or .Values.secrets.jwtSecret .Values.secrets.internalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authos.fullname" . }}-secrets
  labels:
    {{- include "authos.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.internalSecret }}
  INTERNAL_SECRET: {{ .Values.secrets.internalSecret | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.global.tenantMode "single") .Values.singleTenant.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.singleTenant.adminPassword | b64enc | quote }}
  {{- end }}
{{- end }}
