apiVersion: v1
kind: Service
metadata:
  name: {{ include "authos.fullname" . }}-api
  labels:
    {{- include "authos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    {{- include "authos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
